# Generated by Django 5.1.7 on 2025-05-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_gasto_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
