# Generated by Django 5.1.7 on 2025-05-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_propina_sesion'),
        ('tasks', '0005_sesion_cantidad_personas'),
    ]

    operations = [
    ]
