# Generated by Django 5.1.7 on 2025-05-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_merge_20250515_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_creadas', to='tasks.usuario'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='cantidad_personas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
