# Generated by Django 5.1.7 on 2025-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_sesion_creador_alter_sesion_cantidad_personas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='participante',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('sesion', 'usuario')},
        ),
    ]
